interface LogoProps{
    src:string,
    name:string
}

interface SkillProps{
    title:string,
    logos:LogoProps[]
}


export const Skill:SkillProps[]= [
    {
        title:"FRONTEND",
        logos:[{
            src:"/icons/javascript-original.svg",
            name:"javascript"
        },
        {
            src:"/icons/react-original.svg",
            name:"react"
        },
        {
            src:"/icons/typescript-original.svg",
            name:"typescript"
        },
        {
            src:"/icons/html5-original.svg",
            name:"html"
        },
        
        {
            src:"/icons/css3-original.svg",
            name:"css"
        },
        {
            src:"/icons/tailwindcss-original.svg",
            name:"tailwindcss"
        },
        {
            src:"/icons/nextjs-original.svg",
            name:"nextjs"
        }
    ]
    },


    {
        title:"BACKEND",
        logos:[{
            src:"/icons/nodejs-original.svg",
            name:"node"
        },
        {
            src:"/icons/express-original.svg",
            name:"express"
        },
        {
            src:"/icons/mongodb-original.svg",
            name:"mongodb"
        },
        {
            src:"/icons/fastapi-original.svg",
            name:"fastApi"
        },
        {
            src:"/icons/python-original.svg",
            name:"python"
        },
        {
            src:"/icons/django-plain.svg",
            name:"django"
        },
        ]
    },
    {
        title:"DATABASE",
        logos:[{
            src:"/icons/mongodb-original.svg",
            name:"mongodb"
        },
        {
            src:"/icons/mysql-original.svg",
            name:"mysql"
        },
        {
            src:"/icons/postgresql-original.svg",
            name:"postgresql"
        }]
    },
    {
        title:"TOOLS",
        logos:[{
            src:"/icons/git-original.svg",
            name:"git"
        },
        {
            src:"/icons/amazonwebservices-original-wordmark.svg",
            name:"aws"
        },
        {
            src:"/icons/docker-original.svg",
            name:"docker"
        }]
    }
]
